.TH GBEMU-AS 1 LOCAL
.SH NAME

gbemu-as - GameBoy [dis]assembler

.SH EXAMPLE

.SH SYNOPSIS

.B gbemu-as [options] FILE

.I option option

.B ["

.I -yy -zz

.B ..."]

.SH AVAILABILITY

All UNIX flavors

.SH DESCRIPTION

gbemu-as is the [dis]assembler of the gbemu project. It
is able to generate GameBoy ROMs from assembly file, or
rebuild assembly files from ROM blobs.

.SH OPTIONS

There are no options, but we'll make some up.

.TP 5

-yy

is one option

.TP

-zz

is another option

.SH AUTHOR

Aurelien Vallee <vallee.aurelien@gmail.com>
